FROM python:3.11-buster

RUN pip install --upgrade pip && \
    pip install pandas numpy plotly krippendorff seaborn jinja2 scipy statsmodels

#RUN pip install --upgrade pip && \
#    pip install scikit-learn && \
#    pip install pingouin && \
#    pip install simpledorff && \
#    pip install openpyxl
