FROM python:3.11-buster

RUN pip install --upgrade pip && \
    pip install pandas numpy plotly krippendorff seaborn jinja2

#RUN pip install --upgrade pip && \
 #    pip install scipy && \
 #    pip install numpy && \
 #    pip install pandas && \
 #    pip install statsmodels && \
 #    pip install jinja2 && \
 #    pip install krippendorff && \
 #    pip install scikit-learn && \
 #    pip install pingouin && \
 #    pip install simpledorff && \
 #    pip install seaborn && \
 #    pip install openpyxl && \
 #    pip install plotly